### ISSUE TITLE
Allow tooltip only

### ISSUE THREAD

**Issue by JakeGinnivan** [lukepearson/vscode-extension-cidr-ip-range#1]
When using this extension in a table it messes up the rendering.

<img width="524" alt="image" src="https://user-images.githubusercontent.com/453152/164163939-f7d32704-e5aa-4fc9-9e70-b5671562651e.png">

It would be great to just allow the tooltip without the code lens

**Comment by lukepearson** [comment]
Hi @JakeGinnivan , thanks for the suggestion! I've added a configuration option that will allow you to toggle the inline code decoration
<img width="541" alt="disabled_inline_decorator" src="https://user-images.githubusercontent.com/2988301/164178559-0fd8eb56-f2d1-466b-bbcd-2c2968028bde.png">

The option defaults to being on, so you'll have to update the configuration with the following in order to disable the decoration
```json
  "cidr-ip-range": {
    "enableDecorator": false
  },
```

Would you mind reviewing the changes and let me know if the fix is suitable?
https://github.com/lukepearson/vscode-extension-cidr-ip-range/pull/2

**Comment by JakeGinnivan** [comment]
Looks good to me, thanks!
